In [1]:

import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
x = np.array([80, 10, 20, 60, 70, 95,90,120 ])
y = np.array([150, 20, 90, 130, 170, 220, 110, 260])

In [3]:
x.shape[0]

8

In [4]:
x

array([ 80,  10,  20,  60,  70,  95,  90, 120])

In [5]:
w = 1

In [6]:
def batch_gradient_descent(X, y_true, epochs, learning_rate = 0.001):

    number_of_features = 1
    
    w = np.ones(shape=(number_of_features))
    b=0
    total_samples = X.shape[0]
    
    cost_list = []
    epoch_list = []
    
    for i in range(epochs):
        y_predicted = w*x + b
        
        w_grad = (2/total_samples)*np.sum(x.T.dot(y_predicted-y_true))
        b_grad = (2/total_samples)*np.sum(y_predicted-y_true)
        
        w = w - learning_rate * w_grad
        b = b - learning_rate * b_grad
        
        cost =np.mean(np.square(y_true-y_predicted))
        
        if i%10==0:
            cost_list.append(cost)
            epoch_list.append(i)
            
            
    return w, b, cost, cost_list, epoch_list

w, b, cost, cost_list, epoch_list = batch_gradient_descent(x,y,x.shape[0],0.00001)
w, b, cost

(array([1.65634396]), 0.008393089792113942, 2320.0854085438486)

In [7]:
w

array([1.65634396])

In [8]:
import random
random.randint(0,6)


6

In [9]:
def stochastic_gradient_descent(x, y_true, epochs, learning_rate = 0.01):
    number_of_features = 1
    w = np.ones(shape=(number_of_features))
    b=0
    total_samples = x.shape[0]
    
    cost_list = []
    epoch_list = []
    
    for i in range(epochs):
        random_index = random.randint(0,total_samples-1)
        sample_x = x[random_index]
        sample_y = y_true[random_index]
        
        y_predicted = w*x + b
    
        w_grad = (2/total_samples)*np.sum(x.T.dot(y_predicted-y_true))
        b_grad = (2/total_samples)*np.sum(y_predicted-y_true)
                                     
    
        w = w - learning_rate * w_grad
        b = b - learning_rate * b_grad
                                     
        cost = np.square(sample_y-y_predicted)
        
        if i%100==0: 
           cost_list.append(cost)
           epoch_list.append(i)
    return w, b, cost, cost_list, epoch_list
                                     
w_sgd, b_sgd, cost_sgd, cost_list_sgd, epoch_list_sgd = stochastic_gradient_descent(x,y,x.shape[0],1000)
w_sgd, b_sgd, cost_sgd        

w, b, cost

(array([1.65634396]), 0.008393089792113942, 2320.0854085438486)